BTCD System/BTCD System/Models/CustomerRequirment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BTCD_System.Models
{
    public class CustomerRequirment
    {
        public int? RequirementId { get; set; }
        public int? CustomerId { get; set; }
        public int? CategoryId { get; set; }
        [Required]
        public int ItemId { get; set; }
        public int GradeId { get; set; }
        [Required]
        public int UOMId { get; set; }
        [Required]
        public DateTime RequiredDate { get; set; }
        [Required]
        public decimal RequiredQty { get; set; }
        [Required]
        public decimal RequiredPrice { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }


        //Reference 
        public string ItemName { get; set; }
        public string GradeDesc { get; set; }
        public string UOMDesc { get; set; }

        public string CustomerName { get; set; }

    }
}

BTCD System/BTCD System/Controllers/CustomerRequirmentController.cs
using BTCD_System.BTCD_DL.Master;
using BTCD_System.BTCD_DL.Transaction;
using BTCD_System.Common;
using BTCD_System.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTCD_System.Controllers
{
    public class CustomerRequirmentController : Controller
    {

        private List<SelectListItem> ListItem;

        private List<CustomerM> lstCustomer;
        private List<CategoryM> lstCategories;
        private List<ItemGradeM> lstItemGrade;
        private List<UnitofMeasurementM> lstUnitofMeasurement;

        private List<AutoComplete> lstAutoComplete;


        private string RequestNo = "";
        private string ErrorMsg = "";

        [Authorize(Roles = "Requrement-Create")]
        public ActionResult Create()
        {
            List<CustomerRequirment> lstCustomerRequirment = new List<CustomerRequirment>();


            ViewBag.Category = GetCategories();
            ViewBag.Customer = GetCustomer();
            ViewBag.UOM = getUOM();
       

            return View(lstCustomerRequirment);
        }

        [Authorize(Roles = "Requrement-Create")]
        [HttpPost]
        [ActionName("Create")]
        public ActionResult Create_Post()
        {
            CustomerRequirment CustomerRequirment = new CustomerRequirment();
            List<CustomerRequirment> lstCustomerRequirment = new List<CustomerRequirment>();

            if (TempData["lstCustomerRequirment"] == null)
                TempData["lstCustomerRequirment"] = lstCustomerRequirment;
            else
                lstCustomerRequirment = TempData["lstCustomerRequirment"] as List<CustomerRequirment>;

            TryUpdateModel(CustomerRequirment);

            if (lstCustomerRequirment.Count > 0)
            {

                //Update customer and create date 
                lstCustomerRequirment.ForEach(e => e.CustomerId = 1);
                lstCustomerRequirment.ForEach(e => e.CreatedBy = commonFunctions.GetTransactionEmployeeCode());

                ErrorMsg = new clsT_CustomerRequirment().SaveCustomerRequirment(lstCustomerRequirment, out RequestNo);


                //Error Found
                if (!string.IsNullOrEmpty(ErrorMsg))
                {
                    TempData["Message"] = new MessageBox { CssClassName = ".alert-danger", Title = "Error!", Message = "Transaction was rollback.Try again." };

                    ViewBag.Category = GetCategories();
                    ViewBag.Customer = GetCustomer();
                    ViewBag.UOM = getUOM();

                    TempData["lstCustomerRequirment"] = lstCustomerRequirment;

                    return View(lstCustomerRequirment);
                }
                else
                {
                    
                    TempData["lstCustomerRequirment"] = null;

                    TempData["Message"] = new MessageBox { CssClassName = ".alert-success", Title = "Success!", Message = "Your Customer Requirement No: " + RequestNo };

                    return RedirectToAction("Create");
                }


            }
            else
            {

                ViewBag.Category = GetCategories();
                ViewBag.Customer = GetCustomer();
                ViewBag.UOM = getUOM();

                TempData["Message"] = new MessageBox { CssClassName = ".alert-warning", Title = "Warning!", Message = "Request details not found." };

                TempData["lstCustomerRequirment"] = lstCustomerRequirment;

                return View(lstCustomerRequirment);
            }
        }



        public ActionResult PartialRequiredItem()
        {
            CustomerRequirment CustomerRequirment = new CustomerRequirment();
            List<CustomerRequirment> lstCustomerRequirment = new List<CustomerRequirment>();

            TryUpdateModel(CustomerRequirment);

            if (TempData["lstCustomerRequirment"] == null)
                TempData["lstCustomerRequirment"] = lstCustomerRequirment;
            else
                lstCustomerRequirment = TempData["lstCustomerRequirment"] as List<CustomerRequirment>;


            if (ModelState.IsValid)
            {

                if (!lstCustomerRequirment.Exists(e => e.ItemId == CustomerRequirment.ItemId))
                {

                    CustomerRequirment.ItemName = new clsM_Item().GetItemByItemId(CustomerRequirment.ItemId).ItemName;
                    CustomerRequirment.GradeDesc = new clsM_Grade().GetItemGradeByGradeId(CustomerRequirment.GradeId).GradeDescription;
                    CustomerRequirment.UOMDesc = new clsM_UOM().GetUnitofMeasurementFromId(CustomerRequirment.UOMId).UOMName;

                    lstCustomerRequirment.Add(CustomerRequirment);
                }
                else
                    TempData["Message"] = new MessageBox { CssClassName = ".alert-warning", Title = "Warning!", Message = "This item exist in the list." };

            }
            else
                TempData["Message"] = new MessageBox { CssClassName = ".alert-warning", Title = "Warning!", Message = "Missing some details." };


            int Row = 0;
            lstCustomerRequirment.ForEach(e => e.RequirementId = (Row = Row + 1));

       
            TempData["lstCustomerRequirment"] = lstCustomerRequirment;

            return PartialView("_PartialItemDetails", lstCustomerRequirment);

        }


        [HttpPost]
        public ActionResult PartialEditQty(int? ItemId, int Qty)
        {

            List<CustomerRequirment> lstCustomerRequirment = new List<CustomerRequirment>();

            if (TempData["lstCustomerRequirment"] == null)
                TempData["lstCustomerRequirment"] = lstCustomerRequirment;
            else
                lstCustomerRequirment = TempData["lstCustomerRequirment"] as List<CustomerRequirment>;


            if (ItemId != null && Qty > 0)
            {
                if(lstCustomerRequirment.Count > 0)
                    lstCustomerRequirment.Where(e => e.ItemId == ItemId).ToList().ForEach(e => e.RequiredQty = Qty);      
            }
            else
                TempData["Message"] = new MessageBox { CssClassName = ".alert-warning", Title = "Warning!", Message = "Invalid requested qty." };


            int Row = 0;
            lstCustomerRequirment.ForEach(e => e.RequirementId = (Row = Row + 1));

            TempData["lstCustomerRequirment"] = lstCustomerRequirment;

            return PartialView("_PartialItemDetails", lstCustomerRequirment);
        }



        [HttpPost]
        public ActionResult PartialEditPrice(int? ItemId, decimal Price)
        {

            List<CustomerRequirment> lstCustomerRequirment = new List<CustomerRequirment>();

            if (TempData["lstCustomerRequirment"] == null)
                TempData["lstCustomerRequirment"] = lstCustomerRequirment;
            else
                lstCustomerRequirment = TempData["lstCustomerRequirment"] as List<CustomerRequirment>;


            if (ItemId != null && Price > 0)
            {
                if (lstCustomerRequirment.Count > 0)
                    lstCustomerRequirment.Where(e => e.ItemId == ItemId).ToList().ForEach(e => e.RequiredPrice = Price);
            }
            else
                TempData["Message"] = new MessageBox { CssClassName = ".alert-warning", Title = "Warning!", Message = "Invalid requested price." };


            int Row = 0;
            lstCustomerRequirment.ForEach(e => e.RequirementId = (Row = Row + 1));

            TempData["lstCustomerRequirment"] = lstCustomerRequirment;

            return PartialView("_PartialItemDetails", lstCustomerRequirment);
        }


        [HttpPost]
        public ActionResult PartialDeleteItem(int ItemId)
        {
            List<CustomerRequirment> lstCustomerRequirment = new List<CustomerRequirment>();

            if (TempData["lstCustomerRequirment"] == null)
                TempData["lstCustomerRequirment"] = lstCustomerRequirment;
            else
                lstCustomerRequirment = TempData["lstCustomerRequirment"] as List<CustomerRequirment>;


            if (ItemId != 0)
            {

                if (lstCustomerRequirment != null)
                {
                    lstCustomerRequirment.Remove(lstCustomerRequirment.SingleOrDefault(e => e.ItemId == ItemId));
                }
            }

            int Row = 0;
            lstCustomerRequirment.ForEach(e => e.RequirementId = (Row = Row + 1));

            TempData["lstCustomerRequirment"] = lstCustomerRequirment;

            return PartialView("_PartialItemDetails", lstCustomerRequirment);
        }



        [NonAction]
        private List<SelectListItem> GetCustomer()
        {
            ListItem = new List<SelectListItem>();
            lstCustomer = new clsM_Customer().GetAllCustomers();

            foreach (CustomerM Customer in lstCustomer)
            {
                ListItem.Add(new SelectListItem { Value = Customer.CustomerId.ToString(), Text = Customer.CustomerName });

            }

            return ListItem;
        }

        [NonAction]
        private List<SelectListItem> GetCategories()
        {
            ListItem = new List<SelectListItem>();
            lstCategories = new clsM_Category().GetAllCategories();

            foreach (CategoryM Category in lstCategories)
            {
                ListItem.Add(new SelectListItem { Value = Category.CategoryId.ToString(), Text = Category.CategoryName });

            }

            return ListItem;
        }


        [NonAction]
        private List<SelectListItem> GetItemGrade(int ItemId)
        {
            ListItem = new List<SelectListItem>();

BTCD System/BTCD System/Views/CustomerRequirment/Create.cshtml
@model IEnumerable<BTCD_System.Models.CustomerRequirment>
@using BTCD_System.Common

@{
    ViewBag.Title = "Customer Requirement - New Customer Requirement";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Customer Requirement
        <small>Optional description</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Requirement</a></li>
        <li class="active">Customer Requirement</li>
    </ol>
</section>


<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->
    @using (Html.BeginForm("Create", "CustomerRequirment", FormMethod.Post, new { @Id = "frmCustomerRequirment" }))
    {
        @Html.AntiForgeryToken()

        <div class="box box-default">
            <div class="box-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">&nbsp;Save&nbsp;&nbsp;</button>
                            <button type="reset" class="btn btn-success">&nbsp;Reset&nbsp;&nbsp;</button>
                            <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("Cancel", "CustomerRequirment")'"> Cancel  </button>
                        </div>

                    </div>
                </div>
            </div>
        </div>


        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Customer Details</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <!-- /.box-header -->

            <div class="box-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Item Category</label>
                            @Html.DropDownListFor(model => model.SingleOrDefault().CustomerId, (IEnumerable<SelectListItem>)(ViewBag.Customer), "Select Customer", new { @class = "form-control select2", @style = "width: 100%;", @Id = "CustomerId", required = "required" })
                        </div>
                    </div>
                </div>
            </div>



        </div>


    }

    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title">Requirment Item</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
        </div>
        <!-- /.box-header -->
         @using (Html.BeginForm(null, null, FormMethod.Post))
         {
             BTCD_System.Models.CustomerRequirment objCustomerRequirment = new BTCD_System.Models.CustomerRequirment();
             Html.RenderPartial("_PartialItemRequirment", objCustomerRequirment);
         }
    </div>


    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title">Requirment Item Detail(s)</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
        </div>
        <!-- /.box-header -->
        <div id="divPartialView">
            @{ Html.RenderPartial("_PartialItemDetails", Model); }
        </div>
    </div>


</section>
<!-- /.content -->

@*@if (TempData["Message"] != null)
{
    MessageBox UserMessage = (MessageBox)TempData["Message"];
    @Html.Raw("<script>bootbox.alert('" + UserMessage.Message + "');</script>");
}*@




<script>
    $(".decimal").keypress(function (e) {
        var keyCode = (e.which) ? e.which : e.keyCode;
        if ((keyCode >= 48 && keyCode <= 57) || (keyCode == 8))
            return true;
        else if (keyCode == 46) {
            var curVal = document.activeElement.value;
            if (curVal != null && curVal.trim().indexOf('.') == -1)
                return true;
            else
                return false;
        }
        else
            return false;
    });


</script>



BTCD System/BTCD System/Views/CustomerRequirment/_PartialItemDetails.cshtml
@model  IEnumerable<BTCD_System.Models.CustomerRequirment>
@using BTCD_System.Common

<table id="tblItemDetails" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Action</th>
            <th>#</th>
            <th style="display: none;">Item Id</th>
            <th>Item</th>
            <th>Grade</th>
            <th>UOM</th>
            <th>Required Date</th>
            <th>Required Qty</th>
            <th>Required Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (BTCD_System.Models.CustomerRequirment CustomerRequirment in Model)
            {
            <tr>
                <td>
                    <div>
                        <button type="button" class="btn btn-danger btn-xs glyphicon glyphicon-trash DeleteBtn" id="btnDelete"></button>
                    </div>
                </td>
                <td class="clsRowId">@CustomerRequirment.RequirementId</td>
                <td class="clsItemId" style="display: none;">@CustomerRequirment.ItemId</td>
                <td>@CustomerRequirment.ItemName</td>
                <td>@CustomerRequirment.GradeDesc</td>
                <td>@CustomerRequirment.UOMDesc</td>
                <td>@CustomerRequirment.RequiredDate</td>
                <td class="clsQty"><input type="number" value="@CustomerRequirment.RequiredQty" class="txtQty decimal" /></td>
                <td class="clsPrice"><input type="number" value="@CustomerRequirment.RequiredPrice" class="txtPrice decimal" /></td>
            </tr>
        }
    </tbody>

</table>

@if (TempData["Message"] != null)
{
    MessageBox UserMessage = (MessageBox)TempData["Message"];
    @Html.Raw("<script>bootbox.alert('" + UserMessage.Message + "');</script>");
}

<script>
    $('.clsQty').change(function () {
        var $row = $(this).closest("tr");
        var ItemId = $row.find(".clsItemId").text();
        var Qty = $(this).closest('tr').find('.txtQty').val();


        if (Qty <= 0) {
            bootbox.alert('Invalid required qty.');
        }
        else {
            $.ajax({
                url: '@Url.Action("PartialEditQty", "CustomerRequirment")',
                type: "POST",
                data: { ItemId: ItemId, Qty: Qty },
                success: function (result) {
                    $("#divPartialView").html(result);
                }
            });
        }
    });

    $('.clsPrice').change(function () {
        var $row = $(this).closest("tr");
        var ItemId = $row.find(".clsItemId").text();
        var Price = $(this).closest('tr').find('.txtPrice').val();


        if (Price <= 0) {
            bootbox.alert('Invalid required Price.');
        }
        else {
            $.ajax({
                url: '@Url.Action("PartialEditPrice", "CustomerRequirment")',
                type: "POST",
                data: { ItemId: ItemId, Price: Price },
                success: function (result) {
                    $("#divPartialView").html(result);
                }
            });
        }
    });


    $(document).ready(function () {
        $(".DeleteBtn").click(function () {

            var $row = $(this).closest("tr");
            var ItemId = $row.find(".clsItemId").text();

            $.ajax({
                url: '@Url.Action("PartialDeleteItem", "CustomerRequirment")',
                type: "POST",
                data: { ItemId: ItemId },
                success: function (result) {
                    $("#divPartialView").html(result);
                }
            });


        });
    });


    $(".decimal").keypress(function (e) {
        var keyCode = (e.which) ? e.which : e.keyCode;
        if ((keyCode >= 48 && keyCode <= 57) || (keyCode == 8))
            return true;
        else if (keyCode == 46) {
            var curVal = document.activeElement.value;
            if (curVal != null && curVal.trim().indexOf('.') == -1)
                return true;
            else
                return false;
        }
        else
            return false;
    });
</script>

BTCD System/BTCD System/Views/CustomerRequirment/_PartialItemRequirment.cshtml
@model BTCD_System.Models.CustomerRequirment

<div class="box-body">
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label>Item Category</label>
                @Html.DropDownListFor(model => model.CategoryId, (IEnumerable<SelectListItem>)(ViewBag.Category), "Select Category", new { @class = "form-control select2", @style = "width: 100%;", @Id = "CategoryId", required = "required", @onchange = "FillItemsFormCategory();" })
            </div>

            <div class="form-group">
                <label>Item</label>
                @Html.DropDownListFor(model => model.ItemId, Enumerable.Empty<SelectListItem>(), "Select Item", new { @class = "form-control select2", @style = "width: 100%;", @Id = "ItemId", required = "required", @onchange = "FillGradeFromItem();" })
            </div>

            <div class="form-group">
                <label>Grade</label>
                @Html.DropDownListFor(model => model.GradeId, Enumerable.Empty<SelectListItem>(), "Select Item Grade", new { @class = "form-control select2", @style = "width: 100%;", @Id = "GradeId" })
            </div>
        </div>

        <div class="col-md-4">

            <div class="form-group">
                <label>UOM</label>
                @Html.DropDownListFor(model => model.UOMId, (IEnumerable<SelectListItem>)(ViewBag.UOM), "Select UOM", new { @class = "form-control select2", @style = "width: 100%;", @Id = "UOMId", required = "required" })
            </div>

            <div class="form-group">
                <label>Required Date</label>
                @Html.EditorFor(model => model.RequiredDate, new { htmlAttributes = new { @class = "form-control", placeholder = "Required Date", required = "required", @type = "date", @pattern = "(?:19|20)[0-9]{2}-(?:(?:0[1-9]|1[0-2])/(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])/(?:30))|(?:(?:0[13578]|1[02])-31))", @Id = "RequiredDate" } })
            </div>

            <div class="form-group">
                <label>Order Qty</label>
                @Html.EditorFor(model => model.RequiredQty, new { htmlAttributes = new { @class = "form-control decimal", placeholder = "Required Qty", @Id = "RequiredQty", required = "required" } })
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label>Reuest Price</label>
                @Html.EditorFor(model => model.RequiredPrice, new { htmlAttributes = new { @class = "form-control decimal", @Id = "RequiredPrice", placeholder = "Required Price (Rs)", required = "required" } })
            </div>

            <div class="form-group">
                <label>&nbsp;</label><br>
                <div class="btn btn-group">
                    <button type="submit" class="btn btn-primary" onclick="AddItems(this, event);">Add Item</button>
                    <button type="reset" class="btn btn-success">&nbsp;Reset &nbsp;&nbsp;</button>
                </div>
            </div>
            
        </div>

    </div>
</div>

<script type="text/javascript">
    function AddItems(ctrl, event) {
        event.preventDefault();

        if ($('#CategoryId option:selected').val() == "")
        {
            $("#CategoryId").focus();
            bootbox.alert('Please select item category.');
        }
        else if ($('#ItemId option:selected').val() == "")
        {
            $("#ItemId").focus();
            bootbox.alert('Please select item.');
        }
        else if ($('#GradeId option:selected').val() == "")
        {
            $("#GradeId").focus();
            bootbox.alert('Please item grade.');
        }
        else if ($('#UOMId option:selected').val() == "") {
            $("#UOMId").focus();
            bootbox.alert('Please select UOM.');
        }
        else if ($('#RequiredDate').val() == "") {
            $("#RequiredDate").focus();
            bootbox.alert('Please select required date.');
        }
        else if ($('#RequiredQty').val() == "" || $('#RequiredQty').val() <= 0) {
            $("#RequiredQty").focus();
            bootbox.alert('Please enter valid required qty.');
        }
        else if ($('#RequiredPrice').val() == "" || $('#RequiredPrice').val() <= 0) {
            $("#RequiredPrice").focus();
            bootbox.alert('You entered valid required price.');
        }
        else
        {
            $.ajax({
                url: '@Url.Action("PartialRequiredItem", "CustomerRequirment")',
                type: "POST",
                data: $("form").serialize(),
                success: function (result) {
                    $("#divPartialView").html(result);
                }
            });
        }
    }


    function FillItemsFormCategory() {
        var CategoryId = $('#CategoryId').val();

        $.ajax({
            url: '@Url.Action("getItemsFromCategory", "CustomerRequirment")',
            type: "POST",
            dataType: "JSON",
            data: { CategoryId: CategoryId },
            success: function (result) {
                $("#ItemId").html(""); // clear before appending new list
                $("#ItemId").append($('<option></option>').val(null).html("Select Item(s)"));
                $.each(result, function (i, item) {
                    $("#ItemId").append(
                        $('<option></option>').val(item.value).html(item.text));
                });
            }
        });
    }


    function FillGradeFromItem() {
        var ItemId = $('#ItemId').val();

        $.ajax({
            url: '@Url.Action("getGradeFromItem", "CustomerRequirment")',
            type: "POST",
            dataType: "JSON",
            data: { ItemId: ItemId },
            success: function (result) {
                $("#GradeId").html(""); // clear before appending new list
                $("#GradeId").append($('<option></option>').val(null).html("Select Item Grade"));
                $.each(result, function (i, item) {
                    $("#GradeId").append(
                        $('<option></option>').val(item.value).html(item.text));
                });
            }
        });
    }
</script>