BTCD System/BTCD System/Controllers/ReportsTrnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Microsoft.Reporting.WebForms;
using BTCD_System.Models;
using BTCD_System.BTCD_DLL.Reports;

namespace BTCD_System.Controllers
{
    public class ReportsTrnController : Controller
    {
        clsReports reports = new clsReports();
        // GET: Reports

        [Authorize(Roles = "Reports - Reports")]
        public ActionResult Index()
        {
            List<Reports> lstEmsReportses; //= reports.SelectAllReportslist();
            return View();
        }

        [HttpPost]
        public ActionResult Details(string reportName, string serverPath, string reportFolder)
        {
            ReportViewer reportViewer = new ReportViewer();
            reportViewer.ProcessingMode = ProcessingMode.Remote;
            reportViewer.SizeToReportContent = true;
            reportViewer.Width = Unit.Pixel(1100);
            reportViewer.Height = Unit.Pixel(525);

            reportViewer.ServerReport.ReportServerUrl = new Uri(serverPath);
            reportViewer.ServerReport.ReportPath = @"/" + reportFolder + @"/" + reportName ;

            ViewBag.ReportViewer = reportViewer;

            return View();
            //return Redirect("http://www.google.com");
        }

        // GET: Reports/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reports/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reports/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Reports/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reports/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Reports/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BTCD System/BTCD System/Views/ReportsTrn/Details.cshtml
@using ReportViewerForMvc;


@{
    ViewBag.Title = "Report";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


@*<iframe src= @ViewBag.ReportLink.ToString() width="100%" height="525" sandbox="allow-same-origin"></iframe>*@
@*@Html.Partial("~/Views/ASPX/ReportViewer.aspx")*@

<div>
    @Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer);
</div>


BTCD System/BTCD System/Views/ReportsTrn/Index.cshtml
@model IEnumerable<Emblishment_Management_System.Models.emsReports>

@{
    ViewBag.Title = "Reports";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@

<section class="content-header">
    <h1>
        Reports
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Reports</a></li>
        <li class="active">Reports</li>
    </ol>
</section>

<section class="content">

    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title">Select Reports</h3>
        </div>
        <div class="box-body">
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>
                            @Html.DisplayNameFor(model => model.ReportNumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ReportCategory)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ReportDisplayName)
                        </th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @using (Html.BeginForm("Details", "ReportsTrn", FormMethod.Post))
                            {
                                @Html.Hidden("reportName", item.ReportName);
                                @Html.Hidden("serverPath", item.ServerPath);
                                @Html.Hidden("reportFolder", item.ReportFolder);
                                <input type="submit" class="btn btn-default" value="Select"/>
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ReportNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ReportCategory)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ReportDisplayName)
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</section>