BTCD System/BTCD System/Controllers/RequestController.cs
using BTCD_System.BTCD_DL.Master;
using BTCD_System.BTCD_DL.Transaction;
using BTCD_System.Common;
using BTCD_System.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTCD_System.Controllers
{
    public class RequestController : Controller
    {
        private clsT_Stock clsT_Stock = new clsT_Stock();
        private clsT_Bids clsT_Bids = new clsT_Bids();
        private List<StockM> lstStock;
        private List<RequestT> lstRequest;
        private StockM Stock;
        private BidsM Bids;

        private List<SelectListItem> ListItem;
        private List<LocationM> lstLocation;
        private List<ItemGradeM> lstItemGrade;
        private List<UnitofMeasurementM> lstUnitofMeasurement;


        private string RequestNo = "";
        private string ErrorMsg = "";

        // GET: Request
        [Authorize(Roles = "Create-Request")]
        [HttpPost]
        public ActionResult Create(int StockId)
        {
            Stock = new clsT_Stock().GetStockDetailByStockId(StockId);
            Bids = new BidsM { StockId = Stock.StockId, ItemId = Stock.ItemId, ItemCode = Stock.ItemCode, ItemName = Stock.ItemName, LocationId = Stock.LocationId, GradeId = Stock.GradeId, UOMId = Stock.UOMId, Quantity = Stock.Quantity, UnitPrice = Stock.UnitPrice };

            ViewBag.Location = getLocation();
            ViewBag.Grade = GetItemGrade(Stock.ItemId);
            ViewBag.UOM = getUOM();

            return View(Bids);
        }


        [Authorize(Roles = "Create-Request")]
        [HttpPost]
        public ActionResult SaveRequest()
        {
            BidsM Bids = new BidsM();
            Bids.RequestedBy = commonFunctions.GetTransactionEmployeeCode();
            TryUpdateModel(Bids);
            
            if (ModelState.IsValid)
            {
               

                ErrorMsg = clsT_Bids.SaveRequest(Bids, out RequestNo);


                if (!string.IsNullOrEmpty(ErrorMsg))
                {
                    TempData["Message"] = new MessageBox { CssClassName = ".alert-danger", Title = "Error!", Message = "Transaction was rollback.Try again." };

                    ViewBag.Location = getLocation();
                    ViewBag.Grade = GetItemGrade(Bids.ItemId);
                    ViewBag.UOM = getUOM();

                    return RedirectToAction("Create", Bids.StockId);
                }
                else
                {

                    ViewBag.Location = getLocation();
                    ViewBag.Grade = GetItemGrade(Bids.StockId);
                    ViewBag.UOM = getUOM();

                    TempData["Message"] = new MessageBox { CssClassName = ".alert-success", Title = "Success!", Message = "Your Request No: " + RequestNo };

                    return RedirectToAction("ViewStock", "Stock");
                }
            }

            return View();

        }


        [Authorize(Roles = "View-Request")]
        [HttpPost]
        public ActionResult ViewRequest(int StockId)
        {
            lstRequest = new List<RequestT>();

            if (StockId != 0)
            {
                lstRequest = clsT_Bids.ViewRequest(StockId);
            }

            return View(lstRequest);
        }


        [NonAction]
        private List<SelectListItem> getLocation(string SelectedItem = null, string DisabledItem = null)
        {
            ListItem = new List<SelectListItem>();
            lstLocation = new clsM_Location().GetAllLocations();

            foreach (LocationM Location in lstLocation)
            {
                ListItem.Add(new SelectListItem { Value = Location.LocationId.ToString(), Text = Location.LocationName, Selected = Location.LocationId.ToString() == SelectedItem ? true : false, Disabled = Location.LocationId.ToString() == DisabledItem ? true : false });

            }

            return ListItem;
        }


        [NonAction]
        private List<SelectListItem> GetItemGrade(int ItemId)
        {
            ListItem = new List<SelectListItem>();
            lstItemGrade = new clsM_Grade().GetItemGradeByItemId(ItemId);

            foreach (ItemGradeM ItemGrade in lstItemGrade)
            {
                ListItem.Add(new SelectListItem { Value = ItemGrade.GradeId.ToString(), Text = ItemGrade.GradeDescription });

            }

            return ListItem;
        }

        [NonAction]
        private List<SelectListItem> getUOM(string SelectedItem = null, string DisabledItem = null)
        {
            ListItem = new List<SelectListItem>();
            lstUnitofMeasurement = new clsM_UOM().GetAllUnitofMeasurement();

            foreach (UnitofMeasurementM UnitofMeasurement in lstUnitofMeasurement)
            {
                ListItem.Add(new SelectListItem { Value = UnitofMeasurement.UOMId.ToString(), Text = UnitofMeasurement.UOMName, Selected = UnitofMeasurement.UOMId.ToString() == SelectedItem ? true : false, Disabled = UnitofMeasurement.UOMId.ToString() == DisabledItem ? true : false });

            }

            return ListItem;
        }



        [HttpPost]
        public ActionResult Accept(int RequirementId,int StockId)
        {
            if (RequirementId != 0)
            {
                clsT_Bids.ApproveRequest(RequirementId);
            }

            return RedirectToAction("ViewMyStock", "Stock");
        }



        [HttpPost]
        public ActionResult Reject(int RequirementId, int StockId)
        {
            if (RequirementId != 0)
            {
                clsT_Bids.RejectRequest(RequirementId);
            }

            return RedirectToAction("ViewMyStock", "Stock");
        }
    }
}

BTCD System/BTCD System/Views/Request/Create.cshtml
@model BTCD_System.Models.StockM
@using BTCD_System.Common

@{
    ViewBag.Title = "Request - New Request";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Customer Request
        <small>Optional description</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Request</a></li>
        <li class="active">Bid</li>
    </ol>
</section>


<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->
    @using (Html.BeginForm("SaveRequest", "Request", FormMethod.Post, new { @Id = "frmRequest" }))
    {
        @Html.AntiForgeryToken()

        <div class="box box-default">
            <div class="box-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">&nbsp;Save&nbsp;&nbsp;</button>
                            <button type="reset" class="btn btn-success">&nbsp;Reset&nbsp;&nbsp;</button>
                            <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("Cancel", "Request")'"> Cancel  </button>
                        </div>

                    </div>
                </div>
            </div>
        </div>


        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Stock Details</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <!-- /.box-header -->

            <div class="box-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Item Code</label>
                            @Html.EditorFor(model => model.ItemCode, new { htmlAttributes = new { @class = "form-control decimal", placeholder = "Item Code", disabled = "disabled" } })
                            @Html.HiddenFor(Model => Model.ItemId)
                            @Html.HiddenFor(Model => Model.StockId)
                        </div>

                        <div class="form-group">
                            <label>Item Description</label>
                            @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control decimal", placeholder = "Item Name", disabled = "disabled" } })
                        </div>

                        <div class="form-group">
                            <label>Location</label>
                            @Html.DropDownListFor(model => model.LocationId, (IEnumerable<SelectListItem>)(ViewBag.Location), "Select Location", new { @class = "form-control select2", @style = "width: 100%;", disabled = "disabled" })
                        </div>


                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Grade</label>
                            @Html.DropDownListFor(model => model.GradeId, (IEnumerable<SelectListItem>)(ViewBag.Grade), "Select Item Grade", new { @class = "form-control select2", @style = "width: 100%;" , disabled = "disabled" })
                        </div>


                        <div class="form-group">
                            <label>UOM</label>
                            @Html.DropDownListFor(model => model.UOMId, (IEnumerable<SelectListItem>)(ViewBag.UOM), "Select UOM", new { @class = "form-control select2", @style = "width: 100%;", disabled = "disabled" })
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Unit Price</label>
                            @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control decimal", placeholder = "Unit Price (Rs)", disabled = "disabled" } })
                        </div>

                        <div class="form-group">
                            <label>Quantity</label>
                            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control decimal", placeholder = "Quantity", disabled = "disabled" } })
                        </div>

                    </div>


                </div>
            </div>
        </div>

        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">My Request</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <!-- /.box-header -->

            <div class="box-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Order Qty</label>
                            @Html.EditorFor(model => model.RequestQuantity, new { htmlAttributes = new { @class = "form-control decimal", placeholder = "Order Qty" , required = "required" } })
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Reuest Price</label>
                            @Html.EditorFor(model => model.RequestUnitPrice, new { htmlAttributes = new { @class = "form-control decimal", placeholder = "Request Price (Rs)" , required = "required" } })
                        </div>
                    </div>
     
                </div>
            </div>
        </div>



    }


</section>
<!-- /.content -->

@if (TempData["Message"] != null)
{
    MessageBox UserMessage = (MessageBox)TempData["Message"];
    @Html.Raw("<script>bootbox.alert('" + UserMessage.Message + "');</script>");
}




<script>
    $(".decimal").keypress(function (e) {
        var keyCode = (e.which) ? e.which : e.keyCode;
        if ((keyCode >= 48 && keyCode <= 57) || (keyCode == 8))
            return true;
        else if (keyCode == 46) {
            var curVal = document.activeElement.value;
            if (curVal != null && curVal.trim().indexOf('.') == -1)
                return true;
            else
                return false;
        }
        else
            return false;
    });

</script>


BTCD System/BTCD System/Views/Request/ViewRequest.cshtml
@model IEnumerable<BTCD_System.Models.RequestT>
@using BTCD_System.Models;
@{
    ViewBag.Title = "Stock Request Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
         Stock Request
        <small>Optional description</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="#"><i class="fa fa-dashboard"></i>Transaction</a>
        </li>
        <li class="active">Stock Request</li>
    </ol>
    <style>
        form {
            display: inline;
        }
    </style>
</section>


<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->


    <div class="box box-default">
        <div class="box-body">
            <div class="row">
                <div class="col-lg-12 btn-container-right">
                    <div class="btn-group">
                        @using (Html.BeginForm("Index", "Home", FormMethod.Get))
                        {
                            <button type="submit" class="btn btn-warning"> Cancel  </button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title">Stock Request Details</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12">

                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="MyStock" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th style="display: none;">Request Code</th>
                                    <th style="display: none;">Stock Id</th>
                                    <th>Item </th>
                                    <th>Item Name</th>
                                    <th>Required Date</th>
                                    <th>Required Qty</th>
                                    <th>Required Price (Rs)</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (RequestT Request in Model)
                                {
                                    <tr>
                                        <td style="display: none;" class="clsRequirementId"> @Request.RequirementId</td>
                                        <td style="display: none;" class="clsStockId"> @Request.StockId</td>
                                        <td> @Request.ItemId</td>
                                        <td> @Request.ItemName</td>
                                        <td> @Request.RequiredDate.ToString("yyyy-MM-dd")</td>
                                        <td> @Request.RequiredQty</td>
                                        <td> @Request.RequiredPrice</td>
                                        <td>
                                            <div class="form-group">
                                                <button type="submit" name="Approved" class="ApprovedBtn btn  btn-success btn-sm btn-flat">Approve</button>
                                                <button type="submit" name="Reject" class="RejectBtn btn btn-danger btn-sm btn-flat">&nbsp;&nbsp;Reject&nbsp;&nbsp;</button>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <!-- /.box -->
                </div>
            </div>
        </div>
    </div>

</section>


<script>
   $(document).ready(function () {
       $(".ApprovedBtn").click(function () {
        var $row = $(this).closest("tr");

        var RequirementId = $row.find(".clsRequirementId").text().trim();
        var StockId = $row.find(".clsStockId").text().trim();

        bootbox.confirm({
            title: "Confirmation",
            message: "Do you want to approve this request?",
            buttons: {
                cancel: {
                    label: '<i class="fa fa-times"></i> Cancel'
                },
                confirm: {
                    label: '<i class="fa fa-check"></i> Confirm'
                }
            },
            callback: function (result) {
                if (result === true) {
                    $.ajax({
                     url: '@Url.Action("Accept", "Request")',
                     type: "POST",
                     data: { RequirementId: RequirementId, StockId: StockId},
                     success: function (result) {
                         location.reload();
                    }
                });
              }
            }
        });
    });
   });

   $(document).ready(function () {
       $(".RejectBtn").click(function () {
           var $row = $(this).closest("tr");

           var RequirementId = $row.find(".clsRequirementId").text().trim();
           var StockId = $row.find(".clsStockId").text().trim();

           bootbox.confirm({
               title: "Confirmation",
               message: "Do you want to reject this request? ",
               buttons: {
                   cancel: {
                       label: '<i class="fa fa-times"></i> Cancel'
                   },
                   confirm: {
                       label: '<i class="fa fa-check"></i> Confirm'
                   }
               },
               callback: function (result) {
                   if (result === true) {

                       $.ajax({
                           url: '@Url.Action("Reject", "Request")',
                           type: "POST",
                           data: { RequirementId: RequirementId, StockId: StockId },
                           success: function (result) {
                               location.reload();
                           }
                       });
                   }
               }
           });
       });
   });

    var table = $('#Stock').DataTable({
        "columnDefs": [
          {
              "targets": [2],
              "visible": true,
              "searchable": false
          },
          {
              "targets": [3],
              "visible": true,
              "searchable": false
          },
          {
              "targets": [4],
              "visible": true,
              "searchable": false
          },
          {
              "targets": [5],
              "visible": true,
              "searchable": false
          }
        ],
        rowReorder: {
            selector: 'td:nth-child(2)'
        },
        responsive: true
    });

</script>