BTCD System/BTCD System/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;


namespace BTCD_System.Controllers
{

    public class LocationController : Controller
    {
        
        public ActionResult Index()
        {

            return View();
        }

    }
}


BTCD System/BTCD System/Views/Location/Create.cshtml

@model Emblishment_Management_System.Models.emsLocationM


@{
    ViewBag.Title = "Location Master - New Location Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Location Master
        <small>Optional description</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Master</a></li>
        <li class="active">Location</li>
    </ol>
</section>

<section class="content">
    <!-- Your Page Content Here -->
    @using (Html.BeginForm("Create", "Location", FormMethod.Post))
    {
        @Html.AntiForgeryToken()


        <div class="box box-default">
            <div class="box-body">
                <div class="row">
                    <div class="col-lg-12 btn-container-right">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">&nbsp;Save&nbsp;&nbsp;</button>
                            <button type="reset" class="btn btn-success">&nbsp;Reset&nbsp;&nbsp;</button>
                            <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("Index", "Location")'"> Cancel  </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Enter New Location Details</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Location Code</label>
                            @Html.EditorFor(model => model.LocationCode, new { htmlAttributes = new { @class = "form-control", placeholder = "Location Code", required = "required" } })
                        </div>


                        <div class="form-group">
                            <label>Location Description</label>
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", placeholder = "Location Description", required = "required" } })
                        </div>

                    </div>
     
                </div>
            </div>
        </div>
    }

</section>
<!-- /.content -->



BTCD System/BTCD System/Views/Location/Edit.cshtml
@model Emblishment_Management_System.Models.emsLocationM


@{
    ViewBag.Title = "Location Master - Update Location Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Location Master
        <small>Optional description</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Master</a></li>
        <li class="active">Location</li>
    </ol>
</section>

<section class="content">
    <!-- Your Page Content Here -->
    @using (Html.BeginForm("Edit", "Location", FormMethod.Post))
    {
        @Html.AntiForgeryToken()


        <div class="box box-default">
            <div class="box-body">
                <div class="row">
                    <div class="col-lg-12 btn-container-right">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">&nbsp;Save&nbsp;&nbsp;</button>
                            <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("Index", "Location")'"> Cancel  </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Update Location Details</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Location Code</label>
                            @Html.EditorFor(model => model.LocationCode, new { htmlAttributes = new { @class = "form-control", placeholder = "Location Code", required = "required", disabled = "disabled", @readonly = "readonly" } })
                            @Html.HiddenFor(model => model.LocationCode)
                        </div>


                        <div class="form-group">
                            <label>Location Description</label>
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", placeholder = "Location Description", required = "required" } })
                        </div>

                    </div>

                </div>
            </div>
        </div>
    }

</section>
<!-- /.content -->

BTCD System/BTCD System/Views/Location/Index.cshtml
@model IEnumerable<Emblishment_Management_System.Models.emsLocationM>

@{
    ViewBag.Title = "Location Master";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Location Master
        <small>Optional description</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Master</a></li>
        <li class="active">Location</li>
    </ol>
    <style>
        form {
            display: inline;
        }
    </style>
</section>


<!-- Main content -->
<section class="content">
    <div class="box box-default">
        <div class="box-body">
            <div class="row">
                <div class="col-lg-12 btn-container-right">
                    <div class="btn-group">
                        @using (Html.BeginForm("Create", "Location", FormMethod.Get))
                        {
                            <button type="submit" class="btn btn-primary">New Location</button>
                            <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("Index", "Home")'"> Cancel  </button>
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>



    <!-- Your Page Content Here -->
    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title">Location Master Details</h3>

            <div class="box-tools pull-right">
                <button type="button" id="f" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12">

                    <div class="box">
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="dtVendors" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Action</th>
                                        <th>Location Code</th>
                                        <th>Location Description</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @using (@Html.BeginForm("Edit", "Location", new { Id = item.ID  }, FormMethod.Get, new { @title = "Edit" }))
                                                {<button type="submit" class="btn  btn-warning btn-xs glyphicon glyphicon-edit"></button>}

                                                @using (@Html.BeginForm("Delete", "Location", new { Id = item.LocationCode }, FormMethod.Post, new { @title = "Delete" }))
                                                {<button type="submit" class="btn btn-danger btn-xs glyphicon glyphicon-trash" data-toggle="confirmation"></button>}
                                            </td>
                                            <td>@Html.DisplayFor(modelItem => item.LocationCode)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Description)</td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </div>
    </div>
</section>

